[package]
name = "routing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
barrage = "0.2.3"
flume = "0.10.14"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
